"""empty message

Revision ID: 0caa79886fd1
Revises: c27f3ed268e3
Create Date: 2024-07-26 16:01:43.140532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caa79886fd1'
down_revision: Union[str, None] = 'c27f3ed268e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'games', ['title'])
    op.create_unique_constraint(None, 'languages', ['title'])
    op.create_unique_constraint(None, 'platforms', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'languages', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    # ### end Alembic commands ###
